#ifndef __JK_GPIO_H
#define __JK_GPIO_H

#include "gd32f4xx.h"

typedef enum JK_GPIO_E_Rcu
{
    JK_GPIO_E_RCU_GPIOA = RCU_GPIOA,
    JK_GPIO_E_RCU_GPIOB = RCU_GPIOB,
    JK_GPIO_E_RCU_GPIOC = RCU_GPIOC,
    JK_GPIO_E_RCU_GPIOD = RCU_GPIOD,
    JK_GPIO_E_RCU_GPIOE = RCU_GPIOE,
    JK_GPIO_E_RCU_GPIOF = RCU_GPIOF,
    JK_GPIO_E_RCU_GPIOG = RCU_GPIOG,
    JK_GPIO_E_RCU_GPIOH = RCU_GPIOH,
    JK_GPIO_E_RCU_GPIOI = RCU_GPIOI,
} JK_GPIO_E_RCU;

typedef enum JK_GPIO_E_Group
{
    JK_GPIO_E_GROUP_GPIOA = GPIOA,
    JK_GPIO_E_GROUP_GPIOB = GPIOB,
    JK_GPIO_E_GROUP_GPIOC = GPIOC,
    JK_GPIO_E_GROUP_GPIOD = GPIOD,
    JK_GPIO_E_GROUP_GPIOE = GPIOE,
    JK_GPIO_E_GROUP_GPIOF = GPIOF,
    JK_GPIO_E_GROUP_GPIOG = GPIOG,
    JK_GPIO_E_GROUP_GPIOH = GPIOH,
    JK_GPIO_E_GROUP_GPIOI = GPIOI,
} JK_GPIO_E_GROUP;

typedef enum JK_GPIO_E_Pin
{

    JK_GPIO_E_PIN_0 = GPIO_PIN_0,
    JK_GPIO_E_PIN_1 = GPIO_PIN_1,
    JK_GPIO_E_PIN_2 = GPIO_PIN_2,
    JK_GPIO_E_PIN_3 = GPIO_PIN_3,
    JK_GPIO_E_PIN_4 = GPIO_PIN_4,
    JK_GPIO_E_PIN_5 = GPIO_PIN_5,
    JK_GPIO_E_PIN_6 = GPIO_PIN_6,
    JK_GPIO_E_PIN_7 = GPIO_PIN_7,
    JK_GPIO_E_PIN_8 = GPIO_PIN_8,
    JK_GPIO_E_PIN_9 = GPIO_PIN_9,
    JK_GPIO_E_PIN_10 = GPIO_PIN_10,
    JK_GPIO_E_PIN_11 = GPIO_PIN_11,
    JK_GPIO_E_PIN_12 = GPIO_PIN_12,
    JK_GPIO_E_PIN_13 = GPIO_PIN_13,
    JK_GPIO_E_PIN_14 = GPIO_PIN_14,
    JK_GPIO_E_PIN_15 = GPIO_PIN_15,

} JK_GPIO_E_PIN;

typedef enum JK_GPIO_E_Af
{
    JK_GPIO_E_AF_0 = GPIO_AF_0,
    JK_GPIO_E_AF_1 = GPIO_AF_1,
    JK_GPIO_E_AF_2 = GPIO_AF_2,
    JK_GPIO_E_AF_3 = GPIO_AF_3,
    JK_GPIO_E_AF_4 = GPIO_AF_4,
    JK_GPIO_E_AF_5 = GPIO_AF_5,
    JK_GPIO_E_AF_6 = GPIO_AF_6,
    JK_GPIO_E_AF_7 = GPIO_AF_7,
    JK_GPIO_E_AF_8 = GPIO_AF_8,
    JK_GPIO_E_AF_9 = GPIO_AF_9,
    JK_GPIO_E_AF_10 = GPIO_AF_10,
    JK_GPIO_E_AF_11 = GPIO_AF_11,
    JK_GPIO_E_AF_12 = GPIO_AF_12,
    JK_GPIO_E_AF_13 = GPIO_AF_13,
    JK_GPIO_E_AF_14 = GPIO_AF_14,
    JK_GPIO_E_AF_15 = GPIO_AF_15,
} JK_GPIO_E_AF;

#endif
